### ISSUE TITLE
Exporting as SVGs

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/Calico-Icon#7]
It would be nice to have the icons also available as separate SVGs so they could be used as vector icons.

This is possible with the Inkscape command line:
```bash
Owner@Bedroom-Desktop MINGW64 ~/Desktop/projects/Calico-Icon (master)
$ inkscape "icons.svg" --export-id="Icon_Sprite" --export-id-only --export-plain-svg="sprite.svg"
```
However, it was spitting out a 16x16 blank canvas before I realized the missing object/group was all the way at the top, outside of the canvas. Upon further inspection it appeared that the y-value in the exported SVG was -275. Looking around a bit, I discovered this is a bug reported 3 years ago:
https://bugs.launchpad.net/inkscape/+bug/1306662

The patch was just recently made to 0.93, which hasn't been released yet. I tried to download 0.92+devel to do this, but it failed me:
```bash
** (inkscape.exe:6300): CRITICAL **: void SPObject::requestModified(unsigned int): assertion 'this->document != NULL' failed

** (inkscape.exe:6300): CRITICAL **: void SPObject::requestModified(unsigned int): assertion 'this->document != NULL' failed

** (inkscape.exe:6300): CRITICAL **: void SPObject::requestModified(unsigned int): assertion 'this->document != NULL' failed

** (inkscape.exe:6300): CRITICAL **: void SPObject::requestModified(unsigned int): assertion 'this->document != NULL' failed

** (inkscape.exe:6300): CRITICAL **: void SPObject::requestModified(unsigned int): assertion 'this->document != NULL' failed
```

Would like to hear other ideas how to splice the SVGs out, because it appears Inkscape just sucks.

**Comment by JoshDreamland** [comment]
InkScape's exporter has always been pretty buggy. There's not much you or I can do about that. You can use an XML parser to extract just the defs and the group containing the icon you want, then reset the transform on that group so it renders correctly. From there, you may even be able to use InkScape's command line to minify the defs section.

If recommend this regardless, because I will be genuinely surprised if InkScape can actually accomplish what you're trying to do, even once that patch ships. You may want to figure out if it's preserving needed defs, and file a bug now if it's not. InkScape has the ability to copy defs dependencies from document to document, but it would actually surprise me if they were invoking those routines correctly during export.

**Comment by RobertBColton** [comment]
Thanks, it's actually not, I did notice that myself this morning. It's copying in a TON of unneeded gradients that aren't even used by ``ICON_SPRITE`` when exporting **only** that ID. It's copying about 15,000 lines of unneeded gradients. So when I say a ton, I mean a TON.

Anyway, yeah, we can get what we want with Inkscape's exporter and just transform the output. But I think it will need to be run twice, once to export, and then a second time to minify. Is there an XML parser for bash? Maybe I should just write this in JS actually.

**Comment by JoshDreamland** [comment]
Okay; this seems really easy to file an InkScape bug against. InkScape preserving all 15K lines of defs is intended behavior if you aren't using `--export-id`. If you were using `--export-id`, and it did not vacuum the defs, just file a bug. Post the bug number here for reference if you do.

The segfault probably warrants a bug regardless. Even if our IDs are somehow ill-formed, InkScape should detect that and report on it rather than exploding.

**Comment by RobertBColton** [comment]
Yeah it's just spitting it out over and over again. Somehow one of those methods must have worked because it did output the file again now, and here's what we have as part of it:

```svg
  <g
     transform="translate(-2.5,-295.5)"
     id="Layer_Icons">
    <g
       transform="translate(0,18)"
       height="18"
       width="18"
       id="Icon_Sprite">
      <path
         d="M 15.467672,13.158811 A 7,7 0 0 1 7.5708683,16.228926 7,7 0 0 1 2.5002474,9.4411493 7,7 0 0 1 7.6842805,2.7395886 7,7 0 0 1 15.528347,5.9420465 L 9.5,9.5 Z"
         style="fill-opacity:1;fill-rule:evenodd"
         id="pac_body" />
      <ellipse
         ry="2"
         rx="1.5"
         cy="6"
         cx="9.5"
         id="pac_eye" />
      <ellipse
         ry="1"
         rx="0.5"
         cy="6.5"
         cx="10"
         id="pac_pupil" />
    </g>
  </g>
```

You can see it's not extracting the ``Icon_Sprite`` from the parent group layer, which we want. But that's good because it would be very easy for us to use an XML parser to transform that away ourselves as a quick workaround.

**Comment by JoshDreamland** [comment]
I'm not sure what's up with the transform on the outer layer... I tried to avoid having a transform at the layer level for this reason. Does it render properly this way? What is the size of the document?

**Comment by RobertBColton** [comment]
Sorry my G710 replacement just got here, I hadn't noticed how much my LEDs faded over 2 years time. This is what I was trying to explain that it was doing. It exports an 18x18 canvas that's blank and the sprite icon is about -295.5 above this canvas. So that's why before I thought it wasn't exporting anything at all. I just randomly had the idea to zoom out and then I finally noticed what was going on.

**Comment by RobertBColton** [comment]
This is what ``--query-all`` gives me:
```bash
Layer_Icons,-8.8817842e-016,-275,13.028347,14
Icon_Sprite,-8.8817842e-016,-275,13.028347,14
pac_body,-8.8817842e-016,-275,13.028347,14
pac_eye,5.5,-273.5,3,4
pac_pupil,7,-272,1,2
```

**Comment by RobertBColton** [comment]
Alright, here's the closest I got so far, removing the parent group layer and or adding the following attributes to the root SVG element:
```svg
width="18"
height="18"
preserveAspectRatio="xMinYMin slice"
viewBox="0 0 18 18">
```
